### ISSUE TITLE
hostnetwork:ture 端口无法访问

### ISSUE THREAD

**Issue by m1iktea** [liangyongz/doris-on-k8s#1]
## 问题描述
be服务部署后，对应机器的hostport并没有启动，但是fe服务部署后，所有的port都正常

## 使用的部署文件
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: doris-be
    k8s.kuboard.cn/name: doris-be
  name: doris-be
  namespace: doris
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: doris-be
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: doris-be
    spec:
      containers:
        - command:
            - /bin/bash
            - '-ce'
            - /opt/be/bin/start_be.sh --daemon;tail -f /dev/null
          env:
            - name: BE_IPADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: '359261016/apache-doris-be:v0.15'
          imagePullPolicy: IfNotPresent
          name: doris-be
          ports:
            - containerPort: 9060
              hostPort: 9060
              protocol: TCP
            - containerPort: 9070
              hostPort: 9070
              protocol: TCP
            - containerPort: 8040
              hostPort: 8040
              protocol: TCP
            - containerPort: 9050
              hostPort: 9050
              protocol: TCP
            - containerPort: 8060
              hostPort: 8060
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 2G
            requests:
              cpu: 200m
              memory: 1G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/be/storage
              name: volume-be
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: volume-be
          persistentVolumeClaim:
            claimName: pvc-doris-be

```
![image](https://user-images.githubusercontent.com/73102617/190122965-922c16d3-b1bb-47f4-b74d-d94a25319410.png)

![image](https://user-images.githubusercontent.com/73102617/190123254-d0bc68a3-1d54-4bb0-8bb6-185141a7d728.png)
